name:                markdown2man
version:             0.1.0.0
github:              "githubuser/markdown2man"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/markdown2man#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- mtl

library:
  source-dirs: src

executables:
  md2man:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - markdown2man

tests:
  test-convert:
    main:                TestConvert
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HTF
    - knob
    - text
    - bytestring
    - markdown2man
